# Generated by Django 5.1 on 2024-08-13 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PP1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podraz', models.CharField(max_length=120, verbose_name='Подразделение 1')),
            ],
        ),
        migrations.CreateModel(
            name='PP2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podraz2', models.CharField(max_length=120, verbose_name='Подразделение 2')),
                ('pp1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp2_set', to='main.pp1', verbose_name='Подразделение 1')),
            ],
        ),
        migrations.CreateModel(
            name='PP3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podraz3', models.CharField(max_length=120, verbose_name='Подразделение 3')),
                ('pp2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp3_set', to='main.pp2', verbose_name='Подразделение 2')),
            ],
        ),
        migrations.CreateModel(
            name='InspDetDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pp1', verbose_name='Подразделение 1')),
                ('pp2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pp2', verbose_name='Подразделение 2')),
                ('pp3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pp3', verbose_name='Подразделение 3')),
                ('data', models.DateField(verbose_name='Дата')),
                ('act_nubmer', models.CharField(max_length=240, verbose_name='Номер акта')),
                ('fio', models.CharField(max_length=120, verbose_name='ФИО проверяющего')),
                ('dolgnost', models.CharField(max_length=240, verbose_name='Должность')),
                ('ab_group', models.CharField(max_length=240, verbose_name='Группа по ЭБ')),
                ('c_level', models.CharField(max_length=120, verbose_name='Уровень контроля')),

            ],
        ),

    ]
