# Generated by Django 5.1 on 2024-08-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopOstDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop_osp', models.CharField(max_length=120, verbose_name='Дополнительный признак')),
            ],
            options={
                'verbose_name': 'Допольнительный признак',
                'verbose_name_plural': 'Дополнительные признаки',
            },
        ),
        migrations.CreateModel(
            name='NTDlinkDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntd_link', models.URLField(verbose_name='Ссылка на НТД')),
            ],
            options={
                'verbose_name': 'Ссылка на НТД',
                'verbose_name_plural': 'Ссылки на НТД',
            },
        ),
        migrations.CreateModel(
            name='OspDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osp', models.CharField(max_length=120, verbose_name='Основной признак')),
            ],
            options={
                'verbose_name': 'Основной признак',
                'verbose_name_plural': 'Основные признаки',
            },
        ),
        migrations.AlterModelOptions(
            name='inspdetdot',
            options={'verbose_name': 'Данные проверяющего', 'verbose_name_plural': 'Данные проверяющих'},
        ),
        migrations.AlterModelOptions(
            name='pp1',
            options={'verbose_name': 'Подразделение 1', 'verbose_name_plural': 'Подразделения 1'},
        ),
        migrations.AlterModelOptions(
            name='pp2',
            options={'verbose_name': 'Подразделение 2', 'verbose_name_plural': 'Подразделения 2'},
        ),
        migrations.AlterModelOptions(
            name='pp3',
            options={'verbose_name': 'Подразделение 3', 'verbose_name_plural': 'Подразделения 3'},
        ),
        migrations.AlterField(
            model_name='inspdetdot',
            name='data',
            field=models.DateField(verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='inspdetdot',
            name='dolgnost',
            field=models.CharField(max_length=240, verbose_name='Должность проверяющего'),
        ),
        migrations.CreateModel(
            name='VoilByDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.IntegerField(verbose_name='#п/п')),
                ('theme', models.IntegerField(verbose_name='Тема #')),
                ('qust', models.IntegerField(verbose_name='Вопроса #')),
                ('vi_viol', models.TextField(verbose_name='Выявленные нарушения')),
                ('photo', models.BinaryField(verbose_name='Фото')),
                ('dop_osp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dopostdot', verbose_name='Основной признак')),
                ('ntd_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ntdlinkdot', verbose_name='Доп признак')),
                ('osp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ospdot', verbose_name='Выявленные нарушения')),
            ],
            options={
                'verbose_name': 'Подразделение 3',
                'verbose_name_plural': 'Подразделения 3',
            },
        ),
    ]
