# Generated by Django 5.1 on 2024-08-15 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dopostdot_ntdlinkdot_ospdot_alter_inspdetdot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voilbydot',
            options={'verbose_name': 'Нарушение по тематике ДОТ', 'verbose_name_plural': 'Нарушения по тематике ДОТ'},
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='dop_osp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dopostdot', verbose_name='Доп. признак'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='np',
            field=models.IntegerField(verbose_name='№п/п'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='ntd_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ntdlinkdot', verbose_name='Ссылка на НТД'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='osp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ospdot', verbose_name='Основной признак'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='qust',
            field=models.IntegerField(verbose_name='Вопрос №'),
        ),
        migrations.AlterField(
            model_name='voilbydot',
            name='theme',
            field=models.IntegerField(verbose_name='Тема №'),
        ),
    ]
